### ISSUE TITLE
Grades for CPT Spot Check

### ISSUE THREAD

**Issue by rayanesouuuu1234** [rayanesouuuu1234/student02#1]
**only got to do one review in class (score: 0.9)**

**Part 1:** 

- [x] Question 1: Database, with database schema 
- [x] Show db.Column changes you have made to model/python file in Visual Studio Code

Screenshot(s): 
![301277896-867c26c4-beb6-42ef-9f19-0659edf5d216](https://github.com/rayanesouuuu1234/student02/assets/109604875/2eebf7e4-4919-45f2-8ec8-a1abacaf068d)

- [x]  Show initialization data code in VSCode
![image](https://github.com/rayanesouuuu1234/student02/assets/109604875/629d84f1-ae73-49da-9ece-f7c076a5a537)
![image](https://github.com/rayanesouuuu1234/student02/assets/109604875/3a81a7d3-fb0f-4581-80d4-252b90735cff)

- [x]  Demo delete database and run ./migrate.sh
![image](https://github.com/rayanesouuuu1234/student02/assets/109604875/237056dd-2e8c-4d61-b855-b7d13053c086)
![image](https://github.com/rayanesouuuu1234/student02/assets/109604875/6e89be74-3332-44d8-b7ba-05bed9507f6c)

- [x] Demo corresponding schema change in SQLite 3
- [x]  Demo initialization data captured in Column in SQLite3
![image](https://github.com/rayanesouuuu1234/student02/assets/109604875/8bb39707-a5ae-47e4-a443-4aa6ca7b2ae1)

**Part 2:** 

- [x]  Question 2: postman with /authentication screen(0.9)

- [x]  Show /authenticate endpoint code in visual studio code
![image](https://github.com/rayanesouuuu1234/student02/assets/109604875/79deb1dc-8155-45a8-92e8-0579ee4934de)

- [x]  Show and Demo /authenticate in Postman..
![image](https://github.com/rayanesouuuu1234/student02/assets/109604875/7f2e4e76-0351-4b1a-8bfe-aea28216d6e1)

- [x] Demo calling to endpoint
- [x]  Show JSON data passed in call
- [x]  Show response window
![image](https://github.com/rayanesouuuu1234/student02/assets/109604875/ee5298ef-c179-4850-b0ce-b6e4c213132e)

- [x]  Show cookie acquired window
![image](https://github.com/rayanesouuuu1234/student02/assets/109604875/88f8f64f-56f6-4ad0-af33-b491d0cadc7c)

- [x]  Cut/Copy/Paste Cookie into jwt.io and show decrypting payload
![image](https://github.com/rayanesouuuu1234/student02/assets/109604875/2b39fc67-e43e-4b05-a328-19c53a13d431)

**Part 3**

- [x]  Show /api CRUD code in Visual Studio Code, expecting READ/GET code
![image](https://github.com/rayanesouuuu1234/student02/assets/109604875/849b2de1-e9e9-4878-83c0-d521f9c3b552)

- [x]  Show and Demo /api READ/GET endpoint in Postman
![image](https://github.com/rayanesouuuu1234/student02/assets/109604875/74624ebf-3f2d-4372-99ec-f8c5527c917b)

- [x] Demo calling to endpoint that requires Cookie
- [x] Show Response/Data
![image](https://github.com/rayanesouuuu1234/student02/assets/109604875/e9cd08e3-05fa-4b3b-a58d-818595d71138)

- [x] Deleting cookie
![image](https://github.com/rayanesouuuu1234/student02/assets/109604875/f74d48fa-f3d6-409a-96ce-34ca60f3e6db)

- [x]  Demo calling endpoint again
- [x]  Show Response/Failure
![image](https://github.com/rayanesouuuu1234/student02/assets/109604875/28c3550f-3863-4534-bd86-1fc717518ec9)
